title: PythonでWebAPIを使ってみよう
summary: WebAPIを使ったPythonプログラミング入門です
topics: [python, webapi, edublocks]
published: true
price: 0
chapters:
  - 01_about
  - 02_edublocks
  - 03_postal-api
  - 04_what-is-json
  - 05_get-from-json
  - 06_postal-to-address
  - 07_input-postal