title: PythonでWebAPIを使ってみよう
summary: WebAPIを使ったPythonプログラミング入門です
topics: [python, webapi, edublocks]
published: false
price: 0
chapters:
  - 00_about
  - 01_edublocks
  - 02_postal-api
  - 03_what-is-json
  - 04_get-from-json
  # - 05_postal-to-address