title: pygameでゲームを作ろう
summary: pygameを使ったPythonプログラミング入門です
topics: [python, pygame]
published: true
price: 0
chapters:
  - 00_about
  - 01_draw_rect
  - 02_draw_character
  - 03_move_character
  - 04_change_direction
  - 05_shoot
  - 06_enemy
  - 07_hit