title: pygameでゲームを作ろう
summary: pygameを使ったPythonプログラミング入門です
topics: [python, pygame]
published: true
price: 0
chapters:
  - 00_about
  - 01_execution
  - 02_draw_rect
  - 03_draw_character
  - 04_move_character
  - 05_change_direction
  - 06_shoot
  - 07_enemy
  - 08_hit
  - 09_hit_player
  - 10_score_and_hp
  - 11_game_over
  - 12_constants_and_boundary
  - 13_multiple_enemies
  - 14_bgm_and_sound
  - 15_class_refactoring
