title: 小さなDXのノート
summary: 身の回りの小さなことからDXを進めるためのヒント集
topics: [DX, デジタル化, IT, コンピュータ, ネットワーク, インターネット, セキュリティ]
published: false
price: 0
chapters:
  - about
  - explore-forms
  - breaking-down-information-silos
  - appendix