title: 小さなDXノート
summary: 身の回りの小さなことからDXを進めるための小さなヒントを集めたノートです
topics: [DX, デジタル化, IT, コンピュータ, ネットワーク, インターネット, セキュリティ]
published: false
price: 0
chapters:
  - about
  - breaking-down-information-silos
